drop table if exists answer_response_assignment cascade;
drop table if exists  general_questions cascade;
drop table if exists  kegiatan cascade;
drop table if exists  kuesioner_mitra cascade;
drop table if exists  mitra cascade;
drop table if exists  pegawai cascade;
drop table if exists  response_assignment cascade;
drop table if exists  roles cascade;
drop table if exists  status_pegawai cascade;
drop table if exists  structure_kuesioner_mitra cascade;
drop table if exists  "user" cascade;
drop table if exists  user_role_bridge cascade;
drop table if exists  products cascade;
drop table if exists  categories cascade;
drop table if exists  categories_products cascade;
drop table if exists  stock_transactions cascade;
drop table if exists  files;